### ISSUE TITLE
Main page interface flickering

### ISSUE THREAD

**Issue by mtrebitsch** [nikosarcevic/CosmOracle#41] opened 2021-12-30 21:45 UTC
When loading the page with my window on full screen, I get the intro page flickering as shown in this screengrab:

https://user-images.githubusercontent.com/9862893/147789575-615a0740-70a8-4685-ae26-ea0081704b3c.mp4

I guess it's due to the auto-scrollbar popping in and out of existence because of some relative size in the CSS, but I haven't looked it up in details in the code.
If relevant, my setup is a Firefox 95.0.1 with no menu bar on an Ubuntu 20.04.3, with a screen resolution 1920x1080. Adding a menu bar back, or a bookmark toolbar removes the issue, and so does rescaling the page (90% does the trick).

Not a big deal, but worth mentioning :-)

**Comment by nikosarcevic** [comment] 2021-12-30 21:47
oh yes - we are aware of that. the jittering is present in general and can be mitigated by changing the browser window size. we will report the bug to the streamlit team (and you can do that as well)

Thanks SO much for taking the time to report and suggest - we are beyond grateful.

**Comment by lonbar** [comment] 2022-01-01 16:45
[Here](https://discuss.streamlit.io/t/ugly-screen-shifting-when-rendering-how-to-avoid-this/7790) is a workaround from streamlit discuss that may be worth to keep in mind.

Although I definitely remember this being an issue, I can't currently reproduce it on Gentoo (Firefox 95.0.1, Chromium 96.0.4664.110), Ubuntu 20.04.02 (Firefox 95.0) and LineageOS 18.1 (Firefox 95.2.0). @nikosarcevic @marcobonici can you maybe reproduce the flickering?

**Comment by marcobonici** [comment] 2022-01-01 17:49
Using Ubuntu 21.10 and Chrome, I do not see the flickering.

**Comment by nikosarcevic** [comment] 2022-01-01 17:50
can you try Robert'S app?

https://share.streamlit.io/rdzudzar/distributionanalyser/main/main.py

**Comment by lonbar** [comment] 2022-01-01 19:45
I can't reproduce it in Robert's app either. I'm going through the commit history to see if I can find a version where it's there, but no luck so far. @mtrebitsch is the flickering still there on your side?

**Comment by mtrebitsch** [comment] 2022-01-02 00:52
I still see the flickering, but I think it's also because I'm using a Gnome extension called "Pixel saver" that removes the title bar, so the total height of the window is a bit different than in vanilla Ubuntu+Firefox.

**Comment by lonbar** [comment] 2022-01-02 14:55
I can reproduce it if I remove my bookmarks toolbar. It's weird that the flickering only appears to be there when the Introduction or Definitions buttons are selected; it's absent for the Cosmological Distances. I'll try to allocate some time today to work on it.

**Comment by marcobonici** [comment] 2022-01-02 16:27
Probably we should point this to the official Streamlit developers. What do you think @lonbar @nikosarcevic ?

**Comment by nikosarcevic** [comment] 2022-01-02 16:31
Absolutely. I think this was mentioned by other people but we can add to the issue

**Comment by lonbar** [comment] 2022-01-07 16:10
It seems that this issue has resolved itself for now, so I'm closing it. Thanks for reporting and verifying this @mtrebitsch!

**Closed by lonbar** 2022-01-07 16:10 UTC
Labels: known issue
